apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-app
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  labels:
    app: postgres
spec:
  replicas: 2
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      volumes:
        - name: test-app
          persistentVolumeClaim:
            claimName: pvc-app
      containers:
      - name: postgres
        image: postgres:latest
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: test-app
          subPath: postgres
        resources:
          requests:
            cpu: "150m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: POSTGRES_PASSWORD
        - name: POSTGRESS_DB
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: POSTGRES_DB
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  type: ClusterIP
  selector:
    app: postgres
  ports:
  - name: name-of-service-port
    protocol: TCP
    port: 8080
    targetPort: 8080