apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin-deployment
  labels:
    app: pgadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgadmin
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      containers:
      - name: pgadmin
        image: elastio/pgadmin:latest
        resources:
          requests:
            cpu: "150m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
        env:
        - name: PGADMIN_DEFAULT_EMAIL
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: PGADMIN_DEFAULT_EMAIL
        - name: PGADMIN_DEFAULT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: PGADMIN_DEFAULT_PASSWORD
        - name: SOFTWARE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: SOFTWARE_PASSWORD
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: pgadmin-service
spec:
  type: ClusterIP
  selector:
    app: pgadmin
  ports:
  - name: name-of-service-port
    protocol: TCP
    port: 8000
    targetPort: 8000
